var one = ["Afg", "Alb", "Alg", "And", "Ang", "Arg", "Arm", "Aus", "Aze", "Bad", "Bah", "Ban", "Bar", "Bav", "Bel", "Ben", "Bol", "Bos", "Bot", "Bra", "Bur", "Bru", "Cab", "Cam", "Can", "Cay", "Cha", "Cen", "Chi", "Col", "Com", "Con", "Cos", "Cro", "Cub", "Cyp", "Cze", "Den", "Dem", "Dji", "Dom", "Ecu", "Eas", "Egy", "El S", "Equ", "Eri", "Est", "Esw", "Eth", "Fed", "Fij", "Fin", "Fra", "Gab", "Gam", "Geo", "Ger", "Gha", "Gra", "Gre", "Gua", "Gui", "Guy", "Hai", "Han", "Hes", "Hol", "Hon", "Hun", "Ice", "Ind", "Ira", "Ire", "Isr", "Ita", "Jam", "Jap", "Jor", "Kaz", "Ken", "Kin", "Kir", "Kor", "Kos", "Kuw", "Kyr", "Lao", "Lat", "Leb", "Les", "Lew", "Lib", "Lie", "Lit", "Lux", "Mad", "Mal", "Mar", "Mau", "Mec", "Mex", "Mic", "Mol", "Mon", "Mor", "Moz", "Nam", "Nas", "Nau", "Nep", "Net", "New", "Nic", "Nig", "Nor", "Nor", "Old", "Oma", "Ora", "Pak", "Pal", "Pan", "Pap", "Par", "Per", "Phi", "Pie", "Pol", "Por", "Qat", "Sai", "Sam", "San", "Sao", "Sau", "Sch", "Sen", "Ser", "Sey", "Sie", "Sin", "Slo", "Sol", "Som", "Sou", "Spa", "Sri", "Sud", "Sur", "Swe", "Swi", "Syr", "Taj", "Tan", "Tha", "Tim", "Tog", "Ton", "Tri", "Tun", "Tur", "Tuv", "Uga", "Ukr", "Uni", "Uru", "Uzb", "Van", "Ven", "Vie", "Wur", "Yem", "Zam", "Zim"]
var two = ["hanistan", "ania", "eria", "orra", "ola", "entina", "enia", "tralia", "tria", "rbaijan", "en", "amas", "rain", "gladesh", "bados", "aria", "arus", "gium", "ize", "in", "ivia", "nia", "swana", "zil", "nei", "nswick", "garia", "ma", "undi", "bodia", "eroon", "ada", "man Islands", "ntral African Republic", "ntral American Federation", "d", "le", "na", "ombia", "oros", "go Free State", "ta Rica", "atia", "a", "rus", "chia", "choslovakia", "ocratic Republic of Congo", "mark", "bouti", "inica", "inican Republic", "t Germany", "ador", "pt", "alvador", "atorial Guinea", "trea", "onia", "atini", "iopia", "eral Government of Germany", "i", "land", "nce", "on", "bia", "rgia", "many", "na", "ece", "nada", "temala", "nea", "ana", "ti", "over", "seatic Republics", "y See", "duras", "gary", "land", "ia", "onesia", "n", "q", "land", "ael", "ly", "aica", "an", "dan", "akhstan", "ya", "gdom of Serbia", "ibati", "ea", "ovo", "ait", "gyzstan", "s", "via", "anon", "otho", " Chew", "eria", "ya", "chtenstein", "huania", "embourg", "agascar", "awi", "aysia", "dives", "i", "ta", "shall Islands", "ritania", "ritius", "klenburg", "ico", "ronesia", "dova", "aco", "golia", "tenegro", "occo", "ambique", "ibia", "ru", "ap", "herlands", " Zealand", "aragua", "er", "eria", "th German Confederation", "th German Union", "th Macedonia", "way", "enburg", "n", "nge Free State", "istan", "au", "ama", "al States", "ua New Guinea", "aguay", "u", "lippines", "dmont", "and", "tugal", "ar", "ublic of Genoa", "ublic of Korea", "ublic of the Congo", "ania", "sia", "nda", "nt Kitts and Nevis", "nt Lucia", "nt Vincent and the Grenadines", "oa", " Marino", " Tome and Principe", "di Arabia", "aumburg", "egal", "bia", "chelles", "erra Leone", "gapore", "vakia", "venia", "oman Islands", "alia", "th Africa", "th Sudan", "in", " Lanka", "an", "iname", "den", "tzerland", "ia", "ikistan", "zania", "iland", "or-Leste", "o", "ga", "nidad and Tobago", "isia", "key", "kmenistan", "alu", " Sicilies", "nda", "aine", "on of Soviet Socialist Republics", "ted Arab Emirates", "ted Kingdom", "guay", "ekistan", "uatu", "ezuela", "tnam", "temberg", "en", "bia", "babwe"]

var randomOne = one[Math.floor(Math.random() * one.length)];
console.log(randomOne);
var randomTwo = two[Math.floor(Math.random() * two.length)];
console.log(randomTwo);

function display(){ 
    var start = randomOne;
    var end = randomTwo;
    document.getElementById("start").innerHTML = start;
    document.getElementById("end").innerHTML = end;
}